name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Or master, depending on your default branch name
    paths:
      - 'Neuroca/docs/**'  # Only trigger when docs are changed
      - '.github/workflows/mkdocs-deploy.yml'  # Or when workflow itself is changed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper dates and last modified info
          
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-minify-plugin
          pip install mkdocs-git-revision-date-localized-plugin 
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-macros-plugin
          pip install mkdocs-redirects
      
      - name: Set up docs directory
        run: |
          python scripts/setup_mkdocs.py
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force
